spring:
logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org.jt: INFO

client:
  id: 8CPm73WMWNHzlRYCIiPKrA
  name: DES test client
  description: test TPP client for DES tests
  application_type: web
  subject_type: public
  scope:
    - AISP
    - PISP
  redirect_uris:
    - https://ulsterbank-tpp.ie/openbanking/cb
  transport_kid: 6TuAkAmkUzGF15LzVH1qEn3341o
  signing_kid: j1eN4fJOrbxS8mB-4RGz2z_Dg0U

registration-jwt:
  audience:
    nwb: https://ob.natwest.useinfinite.io
    rbs: https://ob.rbs.useinfinite.io
    ubn: https://ob.ulsterni.useinfinite.io
    ubr: https://ob.ulster.useinfinite.io
  request_object_encryption_enc: A128CBC-HS256
  request_object_encryption_alg: RSA-OAEP-256
  request_object_signing_alg: RS256
  response_types:
    - code
    - token
    - code id_token
  token_endpoint_auth_method: tls_client_auth
  token_endpoint_signing_alg: RS256
  id_token_signed_response_alg: RS256
  grant_types:
    - authorization_code
    - refresh_token
    - client_credentials

generate-options:
  output_directory: /Users/james/dev/ideaProjects/dynamic-reg/create-registration-jwt/src/main/model/keys
  targets:
    - nwb
    - rbs
    - ubn
    - ubr