spring:
logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org.jt: INFO

client:
  id: oeQyoDP5ewjAoL6SfuKG2K
  name: Registration v31 test
  description: test SSA/client for PSD2 onboarding tests
  application_type: web
  subject_type: public
  scope:
    - AISP
    - PISP
  redirect_uris:
    - https://shatnersbassoon.net/openbanking/cb
    - https://shatnersbassoon.net/openbanking/cb2
  transport_kid: YvJnFzgXAtFwIhGUZN_12w1hDBA
  signing_kid: 9xpKIuc1GDgYfAm1uo7o8DyaoEQ

registration-jwt:
  audience:
    nwb: https://ob.natwest.useinfinite.io
    rbs: https://ob.rbs.useinfinite.io
    ubn: https://ob.ulsterni.useinfinite.io
  request_object_encryption_enc: A128CBC-HS256
  request_object_encryption_alg: RSA-OAEP-256
  request_object_signing_alg: RS256
  response_types:
    - code
    - token
    - code id_token
  token_endpoint_auth_method: tls_client_auth
  token_endpoint_signing_alg: RS256
  id_token_signed_response_alg: RS256
  grant_types:
    - authorization_code
    - refresh_token
    - client_credentials

generate-options:
  output_directory: /Users/james/dev/ideaProjects/dynamic-reg/create-registration-jwt/src/main/resources/keys
  targets:
    - nwb
    - rbs
    - ubn


